# Generated by Django 3.2.7 on 2021-09-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('orden_venta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=150)),
                ('tipo_pago', models.CharField(max_length=30, verbose_name='Tipo de pago')),
                ('tipo_venta', models.CharField(max_length=30, verbose_name='Tipo de venta')),
                ('sol_material', models.CharField(max_length=50, verbose_name='Solicitud material')),
                ('orden_compra', models.CharField(max_length=50)),
                ('correo_contacto', models.CharField(max_length=50, verbose_name='Correo contacto cliente')),
                ('canal_venta', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'OrdenVenta',
                'db_table': 'ORDEN_VENTA',
            },
        ),
    ]
