# Generated by Django 3.2.3 on 2021-09-08 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_procesos_logisticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave_busqueda', models.CharField(max_length=30)),
                ('fecha_planificacion', models.DateField()),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='control_procesos_logisticos.ordenventa')),
            ],
            options={
                'verbose_name': 'Planificacion',
                'db_table': 'PLANIFICACION',
            },
        ),
    ]
